# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build12 and deploy1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run:  dotnet build
      
    - name: Publish
      run: dotnet publish

    - name: Upload WebApp1 Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: WebApp1
        path: /home/runner/work/testforCIDemo2019/testforCIDemo2019/TestWebApplication/bin/Debug/net5.0/publish/
      
    - name: upload production ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./TestWebApplication/githubdemo/Workflows

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
         name: production-files
         path: /home/runner/work/testforCIDemo2019/testforCIDemo2019/TestWebApplication/bin/Debug/net5.0/publish/
      - name: Deploy Release
        uses: actions/build-push-action@v2
        with:
         github_token : ${{secrets.TOKEN}}
         path: ./build
   
  
    


   
  
